import type {
  FilterOptions,
  FunnelDetailData,
  OverviewData,
  UserRow,
} from "./types";

export const filterOptions: FilterOptions = {
  business: ["Payments", "Commerce", "Lending", "Subscriptions"],
  product: ["Checkout", "Wallet", "Storefront", "Billing"],
  subProduct: ["Express Pay", "One-Click", "Guest", "Saved Cards"],
  journey: ["Guest Checkout", "Signup", "KYC Verification", "Reactivation"],
  version: ["v4.1", "v4.0", "v3.8"],
};

export const overviewData: OverviewData = {
  updatedLabel: "updated 2m ago",
  kpis: [
    {
      id: "leads",
      label: "LEADS GENERATED",
      value: "24,810",
      delta: "▲12%",
      deltaTone: "up-good",
      baselineLabel: "vs. prior period · 22,150",
      sparkline: [24, 22, 23, 16, 17, 9, 6],
      sparklineColor: "#c1502e",
    },
    {
      id: "dropoff",
      label: "DROP-OFF %",
      value: "61.4%",
      delta: "▲3.0pt",
      deltaTone: "up-bad",
      baselineLabel: "vs. prior period · 58.4%",
      sparkline: [18, 17, 19, 15, 16, 12, 10],
      sparklineColor: "#c0392b",
    },
    {
      id: "mau",
      label: "MAU",
      value: "182.4K",
      delta: "▲5%",
      deltaTone: "up-good",
      baselineLabel: "vs. prior period · 173.7K",
      sparkline: [22, 20, 21, 18, 15, 13, 11],
      sparklineColor: "#c1502e",
    },
    {
      id: "dau",
      label: "DAU · 23% STICK",
      value: "41.7K",
      delta: "▲0.5%",
      deltaTone: "flat",
      baselineLabel: "vs. prior period · 41.5K",
      sparkline: [15, 16, 14, 15, 14, 15, 14],
      sparklineColor: "#a08a6c",
    },
  ],
  funnel: {
    title: "Signup → Paid funnel",
    convPct: "19.4%",
    steps: [
      { step: 1, label: "Visited", users: 24810, convPct: 100, dropPct: null },
      { step: 2, label: "Signed up", users: 15380, convPct: 62, dropPct: 38 },
      { step: 3, label: "Activated", users: 9070, convPct: 37, dropPct: 41 },
      { step: 4, label: "Paid", users: 4810, convPct: 19, dropPct: 47 },
    ],
  },
  retention: {
    weekLabels: ["W0", "W1", "W2", "W3", "W4"],
    cohorts: [
      { cohortLabel: "Jun1", values: [100, 48, 31, 22, 17] },
      { cohortLabel: "Jun8", values: [100, 46, 29, 20, null] },
      { cohortLabel: "Jun15", values: [100, 44, 28, null, null] },
      { cohortLabel: "Jun22", values: [100, 47, null, null, null] },
    ],
    callout: "W2 is the retention cliff across every cohort.",
  },
  timeToConvert: {
    steps: [
      { label: "Visited", dot: 1, p50: "1.2d", p90: "4.1d", barPct: 35 },
      {
        label: "Signed up",
        dot: 0.62,
        p50: "3.8d",
        p90: "11.2d",
        barPct: 65,
        slow: true,
      },
      { label: "Activated", dot: 0.42, p50: "2.4d", p90: "7.6d", barPct: 48 },
      { label: "Paid", dot: 0, p50: "", p90: "", barPct: 0 },
    ],
    totalLabel: "7.4 days",
    totalDelta: "▼0.8d vs prior",
  },
  opportunity: {
    label: "BIGGEST OPPORTUNITY",
    html: 'Recovering half of the <b style="color:#e88a5f">Signed up → Activated</b> drop would add <b style="color:#e88a5f">~3,150</b> activated users / mo.',
  },
};

const guestCheckoutUsers: UserRow[] = [
  {
    id: "u1",
    name: "Rahul Sharma",
    email: "rahul.s@gmail.com",
    currentStage: "KYC upload",
    stageTone: "danger",
    timeInStage: "2d 4h",
    platform: "App",
    status: "Stuck",
  },
  {
    id: "u2",
    name: "Priya Patel",
    email: "priya.p@outlook.com",
    currentStage: "KYC upload",
    stageTone: "danger",
    timeInStage: "18h",
    platform: "Web",
    status: "Retrying",
  },
  {
    id: "u3",
    name: "Amit Joshi",
    email: "amit.j@company.in",
    currentStage: "KYC upload",
    stageTone: "danger",
    timeInStage: "5d 12h",
    timeInStageDanger: true,
    platform: "App",
    status: "Stuck",
  },
  {
    id: "u4",
    name: "Sneha Reddy",
    email: "sneha.r@gmail.com",
    currentStage: "KYC approved",
    stageTone: "success",
    timeInStage: "—",
    platform: "App",
    status: "Passed",
  },
  {
    id: "u5",
    name: "Vikram Singh",
    email: "v.singh@yahoo.com",
    currentStage: "KYC upload",
    stageTone: "danger",
    timeInStage: "1d 6h",
    platform: "Web",
    status: "Retrying",
  },
];

export const funnelDetailData: FunnelDetailData = {
  id: "guest-checkout",
  name: "Guest Checkout funnel",
  meta: "13 stages · Payments → Checkout → Express Pay · v4.1",
  kpis: {
    totalEntries: "24,810",
    endToEndConv: "7.2%",
    endToEndDelta: "▼1.3pt",
    avgTimeToConvert: "12.6d",
    avgTimeDelta: "▼0.4d",
    biggestDropoffLabel: "KYC Upload",
    biggestDropoffSub: "↓52% of users lost",
  },
  stages: [
    { step: 1, label: "Landing page", users: 24810, convPct: 100, dropPct: null },
    { step: 2, label: "CTA clicked", users: 18360, convPct: 74, dropPct: 26 },
    { step: 3, label: "Email entered", users: 15380, convPct: 62, dropPct: 16 },
    { step: 4, label: "OTP verified", users: 13920, convPct: 56, dropPct: 9 },
    { step: 5, label: "Profile created", users: 11160, convPct: 45, dropPct: 20 },
    { step: 6, label: "KYC started", users: 9070, convPct: 37, dropPct: 19 },
    { step: 7, label: "KYC doc upload", users: 4350, convPct: 18, dropPct: 52, worst: true },
    { step: 8, label: "KYC approved", users: 3870, convPct: 16, dropPct: 11 },
    { step: 9, label: "Cart created", users: 3480, convPct: 14, dropPct: 10 },
    { step: 10, label: "Address entered", users: 2980, convPct: 12, dropPct: 14 },
    { step: 11, label: "Payment method", users: 2610, convPct: 11, dropPct: 12 },
    { step: 12, label: "Order reviewed", users: 2120, convPct: 9, dropPct: 19 },
    { step: 13, label: "Payment complete", users: 1790, convPct: 7.2, dropPct: 16 },
  ],
  dropoffReasons: {
    stageLabel: "STAGE 7 · KYC DOC UPLOAD",
    reasons: [
      { label: "File format unsupported", pct: 34, tone: "danger" },
      { label: "Upload timeout", pct: 28, tone: "danger" },
      { label: "Camera permission denied", pct: 19, tone: "accent" },
      { label: "Abandoned (idle >5m)", pct: 12, tone: "muted" },
      { label: "Other / unknown", pct: 7, tone: "faint" },
    ],
  },
  trend: [
    { week: "W1", value: 6.2 },
    { week: "W2", value: 6.6 },
    { week: "W3", value: 6.9 },
    { week: "W4", value: 6.3 },
    { week: "W5", value: 7.1 },
    { week: "W6", value: 7.4 },
    { week: "W7", value: 7.6 },
    { week: "W8", value: 8.0 },
  ],
  comparison: {
    app: 9.1,
    web: 5.4,
    calloutHtml: "App converts 1.7× better than Web",
    rows: [
      { stage: "Landing", app: "100%", web: "100%" },
      { stage: "Email", app: "68%", web: "54%" },
      { stage: "KYC upload", app: "22%", web: "13%", danger: true },
      { stage: "Payment", app: "9.1%", web: "5.4%" },
    ],
  },
  userTable: {
    stageLabel: "Users at stage 7 · KYC doc upload",
    totalUsers: 4350,
    users: guestCheckoutUsers,
    page: 1,
    pageCount: 870,
  },
};
